### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by yulei-fighting** [eriklindernoren/PyTorch-YOLOv3#222] opened 2019-07-09 02:39 UTC
true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by HaochenW** [comment] 2019-07-12 08:02
The problem is because no object was detected during the first iteration. You have several ways to solve the problem: 1. do not execute the validation process during the first iteration; 2. Increase the number of validation set, or just copy some from the train set. 3. load the pre-trained darknet weights.

**Comment by ChandanVerma** [comment] 2019-07-22 11:40
The issue was solved by doing the multiscale training to false in line no. 38 train.py scripts. By default its True, you can change it to false and the issue will be solved.

**Comment by hyhyni** [comment] 2019-07-28 03:06
The issue can be  solved by change the value in line numbers 150. You can change 0 to 1 and the issue will be solved. For example:
if epoch % opt.evaluation_interval == 0: 
    print("\n---- Evaluating Model ----")
change to 
if epoch % opt.evaluation_interval == 1:
    print("\n---- Evaluating Model ----")

**Comment by Jun-Chow-github** [comment] 2019-08-29 01:39
Resolution provided by hyhyni is helpful, thanks

**Comment by xdwjc** [comment] 2019-12-03 08:38
hyhyni's solution works, thank you very much

**Comment by Flova** [comment] 2021-01-09 21:35
I am closing this because its a duplicate of #178

**Closed by Flova** 2021-01-09 21:35 UTC
