### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by pengzhiwang** [eriklindernoren/PyTorch-YOLOv3#41] opened 2018-06-15 01:19 UTC
[Epoch 0/30, Batch 1830/1833] [Losses: x 0.018887, y 0.017350, w 0.011480, h 0.009068, conf 0.032589, cls 0.145579, total 0.234953, recall: 0.65000]
[Epoch 0/30, Batch 1830/1833] [Losses: x 0.027525, y 0.027824, w 0.010730, h 0.007892, conf 0.054383, cls 0.179986, total 0.308339, recall: 0.81111]
[Epoch 0/30, Batch 1830/1833] [Losses: x 0.012489, y 0.012089, w 0.010546, h 0.007774, conf 0.033698, cls 0.192683, total 0.269278, recall: 0.54545]
[Epoch 0/30, Batch 1830/1833] [Losses: x 0.042511, y 0.042000, w 0.023847, h 0.016442, conf 0.075596, cls 0.151306, total 0.351703, recall: 0.67361]
[Epoch 0/30, Batch 1830/1833] [Losses: x 0.055068, y 0.053277, w 0.060733, h 0.038808, conf 0.099795, cls 0.244854, total 0.552534, recall: 0.65027]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.034622, y 0.033223, w 0.014849, h 0.012658, conf 0.059653, cls 0.104131, total 0.259136, recall: 0.67568]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.038405, y 0.035833, w 0.044459, h 0.039020, conf 0.054494, cls 0.141215, total 0.353426, recall: 0.52899]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.015338, y 0.015971, w 0.013100, h 0.005587, conf 0.035706, cls 0.174440, total 0.260142, recall: 0.52381]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.023167, y 0.022108, w 0.033820, h 0.017704, conf 0.047694, cls 0.193106, total 0.337599, recall: 0.50617]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.014519, y 0.014234, w 0.011042, h 0.005328, conf 0.033018, cls 0.121948, total 0.200090, recall: 0.59259]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.022603, y 0.022197, w 0.011902, h 0.008511, conf 0.041803, cls 0.088609, total 0.195626, recall: 0.61111]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.016306, y 0.014795, w 0.009144, h 0.004840, conf 0.039758, cls 0.154830, total 0.239672, recall: 0.62963]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.021347, y 0.020986, w 0.019330, h 0.012508, conf 0.042181, cls 0.147103, total 0.263455, recall: 0.60870]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.040201, y 0.038973, w 0.015251, h 0.036656, conf 0.073650, cls 0.174954, total 0.379684, recall: 0.54815]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.026244, y 0.026605, w 0.030584, h 0.021944, conf 0.048804, cls 0.160845, total 0.315027, recall: 0.53846]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.010117, y 0.009941, w 0.004098, h 0.005762, conf 0.027249, cls 0.178949, total 0.236117, recall: 0.60000]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.037965, y 0.038500, w 0.014596, h 0.019955, conf 0.056791, cls 0.110870, total 0.278677, recall: 0.64912]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.013917, y 0.013995, w 0.008014, h 0.005817, conf 0.034943, cls 0.167149, total 0.243835, recall: 0.47222]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.027614, y 0.026907, w 0.021914, h 0.014159, conf 0.062784, cls 0.209417, total 0.362795, recall: 0.61111]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.035124, y 0.033940, w 0.018896, h 0.013856, conf 0.060784, cls 0.174728, total 0.337329, recall: 0.71053]
[Epoch 0/30, Batch 1831/1833] [Losses: x 0.023849, y 0.023081, w 0.040256, h 0.029740, conf 0.047857, cls 0.191115, total 0.355898, recall: 0.53333]
[Epoch 0/30, Batch 1832/1833] [Losses: x 0.061831, y 0.061271, w 0.036845, h 0.032102, conf 0.117929, cls 0.158679, total 0.468657, recall: 0.66667]
[Epoch 0/30, Batch 1832/1833] [Losses: x 0.048841, y 0.048758, w 0.083654, h 0.054965, conf 0.089770, cls 0.146247, total 0.472235, recall: 0.59259]
[Epoch 0/30, Batch 1832/1833] [Losses: x 0.036920, y 0.038865, w 0.014582, h 0.023073, conf 0.077787, cls 0.183660, total 0.374887, recall: 0.60000]
[Epoch 0/30, Batch 1832/1833] [Losses: x 0.031886, y 0.031555, w 0.011043, h 0.014374, conf 0.057977, cls 0.117786, total 0.264621, recall: 0.60000]
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    loss = model(img, target)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wang/jiayunpeng/jpy-yolo/PyTorch-YOLOv3-master/models.py", line 194, in forward
    x = module(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: input has less dimensions than expected

**Comment by eriklindernoren** [comment] 2018-06-17 20:01
What dataset are you using? I have only tried with COCO so far and have not encountered this issue.

**Comment by pengzhiwang** [comment] 2018-06-19 06:04
When i want to set the batch to 64, the problem is occured.  Furthermore, you don't use the function of "subdivisions", which will lead to overflow memory.

**Comment by eriklindernoren** [comment] 2019-04-23 02:11
This was caused by a grayscale image in the dataset. Fixed in master.

**Closed by eriklindernoren** 2019-04-23 02:11 UTC
