### ISSUE TITLE
A bug in utils utils.py get_batch_statistics function

### ISSUE THREAD

**Issue by HaochenW** [eriklindernoren/PyTorch-YOLOv3#223] opened 2019-07-12 07:48 UTC
def get_batch_statistics(outputs, targets, iou_threshold):
    """ Compute true positives, predicted scores and predicted labels per sample """
    batch_metrics = []
    for sample_i in range(len(outputs)):

        if outputs[sample_i] is None:
            continue

        output = outputs[sample_i]
        pred_boxes = output[:, :4]
        pred_scores = output[:, 4]
        pred_labels = output[:, -1]

        true_positives = np.zeros(pred_boxes.shape[0])

        annotations = targets[targets[:, 0] == sample_i][:, 1:]
        target_labels = annotations[:, 0] if len(annotations) else []
        if len(annotations):
            detected_boxes = []
            target_boxes = annotations[:, 1:]

            for pred_i, (pred_box, pred_label) in enumerate(zip(pred_boxes, pred_labels)):

                # If targets are found break
                if len(detected_boxes) == len(annotations):
                    break

                # Ignore if label is not one of the target labels
                if pred_label not in target_labels:
                    continue

                iou, box_index = bbox_iou(pred_box.unsqueeze(0), target_boxes).max(0)
                if iou >= iou_threshold and box_index not in detected_boxes:
                    true_positives[pred_i] = 1
                    detected_boxes += [box_index]
        batch_metrics.append([true_positives, pred_scores, pred_labels])
    return batch_metrics

In this function, the bounding box class labels were partly ignored when calculating the IoU. If two bounding box from predicted and ground truth are not with the same label, it will still have chance to match them together and calculate the IoU. As we can see, in the code "iou, box_index = bbox_iou(pred_box.unsqueeze(0), target_boxes).max(0)", each predicted bounding box will match all the target boxes in the one loop, and check whether the biggest IoU will larger than the IoU threshold even though they are in the different labels. There is no label information provided in the above code and no label check in the latter "if" line. The only label check is in the code " if pred_label not in target_labels:", but it has chances to be wrong when one of target labels is matched with pred_label, but the bounding boxes of them are different. So I believe it would be better to add the class selection in the "if" sentence.

**Comment by HaochenW** [comment] 2019-07-12 08:42
I think the code:   iou, box_index = bbox_iou(pred_box.unsqueeze(0), target_boxes).max(0)
  could be changed as:
                iou_list = bbox_iou(pred_box.unsqueeze(0), target_boxes)
                select = (pred_label == target_labels)
                iou_list = iou_list[select]
                iou, box_index = iou_list.max(0)

**Comment by red0orange** [comment] 2020-03-02 13:53
I also found this problem and couldn't understand it. Is this actually a logical error?

**Comment by Flova** [comment] 2021-08-02 13:29
Duplicate of #233

**Closed by Flova** 2021-08-02 13:29 UTC
