### ISSUE TITLE
a batch of background images causes error during calculating cls loss

### ISSUE THREAD

**Issue by IreneLian** [eriklindernoren/PyTorch-YOLOv3#135] opened 2019-04-11 07:00 UTC
Got error if batch images don't contain any ground truth object. (all of them are background.)

mask is an empty tensor,  which leads to empty tcls and torch.argmax error. 

In models.py
202            loss_cls = (1 / nB) * self.ce_loss(pred_cls[mask], torch.argmax(tcls[mask], 1))

==========================
Traceback (most recent call last):
  File "/pytroch-yolo/yolo/train/train.py", line 71, in <module>
    loss = model(images, targets)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/pytroch-yolo/PyTorch-YOLOv3/models.py", line 259, in forward
    x, *losses = module[0](x, targets)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/pytroch-yolo/PyTorch-YOLOv3/models.py", line 202, in forward
    loss_cls = (1 / nB) * self.ce_loss(pred_cls[mask], torch.argmax(tcls[mask], 1))
  File "/usr/local/lib/python3.6/site-packages/torch/functional.py", line 544, in argmax
    return torch._argmax(input, dim, keepdim)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

**Comment by fourth-archive** [comment] 2019-04-11 16:48
@IreneLian I recommend the following YOLOv3 custom dataset tutorial. The accompanying repository works well on MacOS, Windows and Linux, works with multigpu and multithreading, performs inference on images, videos, webcams, and even via a live iOS app, tests to higher mAPs than darknet, including on the latest YOLOv3-SPP, and offers the ability to train custom datasets from scratch to darknet performance.
https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data

**Comment by eriklindernoren** [comment] 2019-04-26 18:07
@IreneLian Could you pull the latest version and try now? Pushed a fix for it here 1fa9a29.

**Comment by anandkanav92** [comment] 2019-09-20 12:03
Still gives the same error. Is there any way to represent training images with no labels( bounding box that is just background)?

**Comment by mpaluy** [comment] 2019-09-20 13:05
> Still gives the same error. Is there any way to represent training images with no labels( bounding box that is just background)?

When I added some images without objects and with empty label files, I got this exception, too. 
What's the correct way to add empty files to the custom training set?

**Comment by uefall** [comment] 2019-09-29 03:17
File "/home/user112/PyTorch-YOLOv3/utils/utils.py", line 294, in build_targets
    best_ious, best_n = ious.max(0)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

similar exception with empty images, is there anyone who solved this?

**Comment by edwardchaos** [comment] 2019-11-07 15:20
You might have to write your own loss function that uses the negative samples

**Comment by Flova** [comment] 2021-02-02 14:18
Duplicate of #339

**Closed by Flova** 2021-02-02 14:18 UTC
