### ISSUE TITLE
The ouput folder is empty

### ISSUE THREAD

**Issue by volcano1995** [eriklindernoren/PyTorch-YOLOv3#140] opened 2019-04-25 08:44 UTC
I tried to run the python2 detect.py --image_folder /data/samples
but the result is:

Namespace(batch_size=1, checkpoint_model=None, class_path='data/coco.names', conf_thres=0.8, config_path='config/yolov3.cfg', image_folder='/data/samples', img_size=416, n_cpu=8, nms_thres=0.4, weights_path='weights/yolov3.weights')

Performing object detection:

Saving images:

And the output folder is empty. Anyone know why?Thanks!

**Comment by zxy20162101** [comment] 2019-04-26 06:13
have u solved that? i meet it too

**Comment by volcano1995** [comment] 2019-04-26 06:19
> have u solved that? i meet it too

I am so pity that no.

**Comment by volcano1995** [comment] 2019-04-26 06:20
> have u solved that? i meet it too

I am so pity that no.

**Comment by selimarikan** [comment] 2019-04-26 08:31
@volcano1995 Are you getting any results/detections in the console? 
``` 
Performing object detection:

Saving images:
```
Do you see any numbers, results etc. between these lines ^^?

**Comment by volcano1995** [comment] 2019-04-26 08:35
> @volcano1995 Are you getting any results/detections in the console?
> 
> ```
> Performing object detection:
> 
> Saving images:
> ```
> 
> Do you see any numbers, results etc. between these lines ^^?

No,there are nothing,just empty. Do you have some solutions?

**Comment by selimarikan** [comment] 2019-04-26 09:56
> > @volcano1995 Are you getting any results/detections in the console?
> > ```
> > Performing object detection:
> > 
> > Saving images:
> > ```
> > Do you see any numbers, results etc. between these lines ^^?
> 
> No,there are nothing,just empty. Do you have some solutions?

It means that you have no detections so nothing to create in the output folder.
This could be caused by many things but most probably:
1. Your model is not trained good enough -> Try reducing your `conf_threshold` to `0.05` in the `detect.py`
2. Your weights are not loaded correctly -> Check your `load_weights` call in the `detect.py`, you might have to change it to `load_state_dict`

**Comment by volcano1995** [comment] 2019-04-26 10:52
> > > @volcano1995 Are you getting any results/detections in the console?
> > > ```
> > > Performing object detection:
> > > 
> > > Saving images:
> > > ```
> > > Do you see any numbers, results etc. between these lines ^^?
> > 
> > 
> > No,there are nothing,just empty. Do you have some solutions?
> 
> It means that you have no detections so nothing to create in the output folder.
> This could be caused by many things but most probably:
> 
>     1. Your model is not trained good enough -> Try reducing your `conf_threshold` to `0.05` in the `detect.py`
> 
>     2. Your weights are not loaded correctly -> Check your `load_weights` call in the `detect.py`, you might have to change it to `load_state_dict`

Thanks a lot!! I have solved the problem. I run **python3 detect.py** only or change the path,they are both available!

**Comment by volcano1995** [comment] 2019-04-26 10:56
> have u solved that? i meet it too

I have solved it by run **python3 detect.py** only or change the **--image_folder /data/samples** to the absolute path such as  '/home/volcano/PyTorch-YOLOv3/data/samples'. They both works.

**Comment by eriklindernoren** [comment] 2019-04-26 16:38
Nice catch. It should have been `python3 detect.py --image_folder data/samples/`, but I had a typo in the README. Fixed now. :)

**Closed by eriklindernoren** 2019-04-26 16:38 UTC
