### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by jinweiLiu** [eriklindernoren/PyTorch-YOLOv3#588] opened 2020-12-09 09:23 UTC

**Comment by XiaoWei0213** [comment] 2020-12-09 09:24
how should i do?

**Comment by XiaoWei0213** [comment] 2020-12-09 09:28
Performing object detection:
Traceback (most recent call last):
  File "detect.py", line 73, in <module>
    input_imgs = Variable(input_imgs.type(Tensor))

**Comment by ethan4335** [comment] 2020-12-10 08:52
you should check your image size and your cuda memory, if you don't have a enough cuda memory, you can use your local memory to train your model.
you can add "device = torch.device('cpu')" to the main function, you will find that your train.py will work on your local memory.

**Comment by ethan4335** [comment] 2020-12-10 08:52
> Performing object detection:
> Traceback (most recent call last):
> File "detect.py", line 73, in
> input_imgs = Variable(input_imgs.type(Tensor))

you should check your image size and your cuda memory, if you don't have a enough cuda memory, you can use your local memory to train your model.
you can add "device = torch.device('cpu')" to the main function, you will find that your train.py will work on your local memory.

**Comment by XiaoWei0213** [comment] 2020-12-11 03:04
> > Performing object detection:
> > Traceback (most recent call last):
> > File "detect.py", line 73, in
> > input_imgs = Variable(input_imgs.type(Tensor))
> 
> you should check your image size and your cuda memory, if you don't have a enough cuda memory, you can use your local memory to train your model.
> you can add "device = torch.device('cpu')" to the main function, you will find that your train.py will work on your local memory.

thanks, i have solved this problem.

**Comment by Flova** [comment] 2021-01-06 17:19
Good to know that the issue is fixed. Out of Memory Issues can often be fixed by reducing the `batch_size`.

**Comment by Flova** [comment] 2021-01-06 17:20
The issue is fixed I, therefore, close the issue now. Feel free to reopen for further questions.

**Closed by Flova** 2021-01-06 17:20 UTC
