### ISSUE TITLE
how should I train models with GPUS

### ISSUE THREAD

**Issue by hanrui15765510320** [eriklindernoren/PyTorch-YOLOv3#342] opened 2019-11-12 07:46 UTC
hello,I have a problem about what should  I do if I want to train with GPU? I use this command"CUDA_VISIBLE_DEVICES=0,1 python3 train.py --data_config config/coco.data  --pretrained_weights weights/darknet53.conv.74",but it's error and I don't know reasons about this issue.

**Comment by hanrui15765510320** [comment] 2019-11-12 08:38
I'm sorry, the code is right,it's my fault

**Comment by ujsyehao** [comment] 2019-11-13 08:21
@hanrui15765510320  It can use multiple GPUS?

**Comment by ujsyehao** [comment] 2019-11-14 03:45
It is unuseful.

**Comment by hanrui15765510320** [comment] 2019-11-15 06:01
> @hanrui15765510320 It can use multiple GPUS?
I can't use multiple GPUS.You can use this command"CUDA_VISIBLE_DEVICES=0,1",but it  looks unuseful for me,i don't know reasons.

**Comment by ujsyehao** [comment] 2019-11-18 02:18
you can refer to https://github.com/ujsyehao/yolov3-multigpu

**Comment by Damon2019** [comment] 2019-11-28 13:23
Hi，can you tell me how to train with a single-gpu.I found that I am using cpu training

**Comment by LittleYuanzi** [comment] 2020-03-05 09:27
> Hi，can you tell me how to train with a single-gpu.I found that I am using cpu trainin
Did you solve this problem, I encountered the same problem.QAQ

**Comment by sakurasakura1996** [comment] 2020-03-16 02:27
> Hi，can you tell me how to train with a single-gpu.I found that I am using cpu training

Did you solve the problem,I tried to run the code on google colab and found that I am using cpu training

**Comment by JQLIANG77** [comment] 2020-06-09 08:29
> > Hi，can you tell me how to train with a single-gpu.I found that I am using cpu training
> 
> Did you solve the problem,I tried to run the code on google colab and found that I am using cpu training

Did you solve it? How can I run it with the single gpu?

**Comment by nnzy11** [comment] 2020-11-25 08:23
> > > Hi，can you tell me how to train with a single-gpu.I found that I am using cpu training
> > 
> > 
> > Did you solve the problem,I tried to run the code on google colab and found that I am using cpu training
> 
> Did you solve it? How can I run it with the single gpu?
 Hello! Did you solve it? How can I run it with the single gpu?

**Comment by Flova** [comment] 2021-08-03 09:47
Duplicate of issue #520

**Closed by Flova** 2021-08-03 09:47 UTC
