### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by LinpengPan** [eriklindernoren/PyTorch-YOLOv3#391] opened 2019-12-24 10:56 UTC
How to train this network with multiple GPUs?

**Comment by jaysonph** [comment] 2020-01-02 17:23
@LinpengPan 
I think you can refer to PyTorch website.
A short example taken from there:
>>> net = torch.nn.DataParallel(model, device_ids=[0, 1, 2])
>>> output = net(input_var)  # input_var can be on any device, including CPU

**Comment by Flova** [comment] 2021-08-03 09:38
Duplicate of #520

**Closed by Flova** 2021-08-03 09:38 UTC
