### ISSUE TITLE
convert onnx

### ISSUE THREAD

**Issue by cqray1990** [eriklindernoren/PyTorch-YOLOv3#552] opened 2020-08-03 14:14 UTC
have you ever convert model to onnx ,i try to convert to onnx,i can export onnx ,but when i test an image the result is wrong

**Comment by Flova** [comment] 2021-01-11 00:42
I will have a look at it

**Comment by Flova** [comment] 2021-01-11 00:53
Closing because its a duplicate of #291

**Closed by Flova** 2021-01-11 00:53 UTC
