### ISSUE TITLE
RuntimeError: reduce failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by Rainayangyang** [eriklindernoren/PyTorch-YOLOv3#209] opened 2019-06-16 14:36 UTC
I made this mistake in training. I checked that it wasn't the BCELoss parameter error, so I don't know what to do. Please help me.
![QQ截图20190616223619](https://user-images.githubusercontent.com/49405041/59565511-2bb86400-9087-11e9-8ad9-4faa9e0d07bd.jpg)

![QQ截图20190616222648](https://user-images.githubusercontent.com/49405041/59565503-14797680-9087-11e9-8d6d-d348cdf91e13.jpg)

**Comment by BloomBerry** [comment] 2019-06-17 05:42
Same here!
---- [Epoch 0/100, Batch 0/14786] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 13           | 26           | 52           |
| loss       | 71.552628    | 69.287781    | 70.698685    |
| x          | 0.081982     | 0.095761     | 0.097411     |
| y          | 0.114656     | 0.081447     | 0.083638     |
| w          | 2.447639     | 0.842779     | 1.058129     |
| h          | 2.727762     | 1.390022     | 1.789845     |
| conf       | 65.440392    | 66.154922    | 66.964203    |
| cls        | 0.740200     | 0.722845     | 0.705461     |
| cls_acc    | 1.89%        | 0.00%        | 1.47%        |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.463119     | 0.486062     | 0.475699     |
| conf_noobj | 0.466011     | 0.474434     | 0.481249     |
+------------+--------------+--------------+--------------+
Total loss 211.53909301757812
---- ETA 3 days, 18:36:37.682694
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=265 error=59 : device-side assert triggered
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [0,0,0], thread: [51,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jang/Downloads/pycharm-community-2018.3.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/train.py", line 105, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/jang/virtualenv/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/models.py", line 259, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/jang/virtualenv/python3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/models.py", line 188, in forward
    ignore_thres=self.ignore_thres,
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/utils/utils.py", line 324, in build_targets
    iou_scores[b, best_n, gj, gi] = bbox_iou(pred_boxes[b, best_n, gj, gi], target_boxes, x1y1x2y2=False)
  File "/home/jang/PycharmProjects/PyTorch-YOLOv3/utils/utils.py", line 199, in bbox_iou
    b1_x1, b1_x2 = box1[:, 0] - box1[:, 2] / 2, box1[:, 0] + box1[:, 2] / 2
RuntimeError: CUDA error: device-side assert triggered

**Comment by kaikaizhu** [comment] 2019-06-19 12:06
I have the same problem!

**Comment by yyx1107** [comment] 2019-07-01 02:37
Because your labels is not from 0 to n-1,check your labels folder.Maybe your labels is from 1 to n.(n is the class numbers of your data) @kaikaizhu  @BloomBerry @Rainayangyang 
For example , if you have "n" class,the txt file is just "0 0.515 0.5 0.21694873 0.18286777","1 0.555 0.4 0.26794873 0.35286777"....
The first class should be 0,....the sec,third is 1,2....until to n-1.

**Comment by kaikaizhu** [comment] 2019-07-01 07:44
@yyx1107 
Thanks a lot.When I ran the program with a single gpu, everything was fine, but when I joined multiple gpus, I made this mistake, and my label started at 0.

**Comment by yyx1107** [comment] 2019-07-02 09:04
Sorry,I ran this only with a single gpu.I'm not very clear about the multiple gpus.

**Comment by yyx1107** [comment] 2019-07-02 10:13
Sorry,I ran this only with a single gpu.I'm not very clear about the multiple gpus. @kaikaizhu

**Comment by Arthur77Wang** [comment] 2019-07-17 08:57
Came across too. For me this error message should be regarded as a data-checking warning but not a bug in code. I traced backwards step by step and finally found something wrong during training like this:
![2019-07-17 16-51-20屏幕截图](https://user-images.githubusercontent.com/13716913/61361488-2717e300-a8b3-11e9-9d2b-be7e082963e4.png)

You can see "nan"s in tw and th in build_targets func, utils/utils.py. This is caused by negative values of gw and gh which were directly generated from GT boxes. And then I found this in label txt:
![2019-07-17 16-07-11屏幕截图](https://user-images.githubusercontent.com/13716913/61361514-3139e180-a8b3-11e9-83fc-237cae230a6e.png)
So It'll be better to check label files first...for me, at least.

**Comment by xiayanqian** [comment] 2019-08-04 14:54
Hello,may I ask how to change the grid_size?your grid_size is 11,22,44,mine is 13,26,52,how to change it?

**Comment by qfzack** [comment] 2019-10-13 04:04
thank you! I have the same problem, which is caused by the negative values in the annotation file

**Comment by LifeIsSoSolong** [comment] 2019-12-16 05:53
I have the same problem when training raw yolov3 using raw coco data. 
1.Because of using raw coco data, so labels have not bugs.
2.I train yolov3 in one gpu.
3.batchsize=4
4.I try lr 1e-4, 5e-5 , the error both occured.
anyone has some advice?

**Comment by Flova** [comment] 2021-04-17 00:17
This part of the code has been updated or removed. I, therefore, close this issue now. Feel free to reopen for further discussion.

**Closed by Flova** 2021-04-17 00:17 UTC
