### ISSUE TITLE
Poetry install 

### ISSUE THREAD

**Issue by ariharasudhanm** [eriklindernoren/PyTorch-YOLOv3#724] opened 2021-07-22 12:20 UTC
/bin/bash: poetry: command not found

When i tried to install poetry by poetry install in google-colab i am landing in this type of error  
/bin/bash: poetry: command not found

But when I tried to do it from command line then its completely successful but I want it to run the training on the google-colab.

Any help would be appreciated.

**Comment by Flova** [comment] 2021-07-22 14:47
Duplicate of #682

**Closed** 2021-07-22 14:48 UTC
