### ISSUE TITLE
Error when training coco @batch 1473, epoch 0

### ISSUE THREAD

**Issue by CaptainEven** [eriklindernoren/PyTorch-YOLOv3#36] opened 2018-06-13 03:19 UTC
Epoch 0/1000, Batch 1473/7329 | Losses: x 0.126482, y 0.129091, w 0.692879, h 0.779148, conf 0.268520, cls 1.789521, total 3.785640
Traceback (most recent call last):
  File "/mnt/diskb/even/yolov3_pytorch/train.py", line 97, in <module>
    for batch_i, (_, imgs, targets) in enumerate(dataloader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/mnt/diskb/even/yolov3_pytorch/utils/datasets.py", line 73, in __getitem__
    h, w, _ = img.shape
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by alexandru-dinu** [comment] 2018-06-13 10:27
Because `img` is a numpy array that wraps the returned PIL Image, I am guessing that `None` is returned, and so `np.array(None).shape` is `()`, hence the `got 0`.

**Comment by CaptainEven** [comment] 2018-06-14 00:52
@alexandru-dinu the training is fine from start, and the error happened @batch 1473....i don't understand

**Comment by chijan-nh** [comment] 2018-10-15 04:09
I got similar issue in detect.py.
The attached data/samples can be run, however, if grayscale images are given as data/samples, then "not enough values to unpack" error is reproduced.
The code `h,w,_=img.shape` caused this error because the grayscale image does not have channels, i.e. , `len(img.shape)==2`.


I think the @Batch 1473 's images are broken (including `None`). The #36 issue may be caused by the dataset. Until @Batch 1472, the dataset is normal, I think.

**Comment by eriklindernoren** [comment] 2019-04-23 02:10
This was caused by a grayscale image in the dataset. It's fixed in master.

**Closed by eriklindernoren** 2019-04-23 02:10 UTC
