### ISSUE TITLE
cls accuracy not changing 

### ISSUE THREAD

**Issue by riyaj8888** [eriklindernoren/PyTorch-YOLOv3#166] opened 2019-05-09 10:44 UTC
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 15           | 30           | 60           |
| loss       | 46.969822    | 53.641315    | 56.019966    |
| x          | 0.089926     | 0.087395     | 0.087266     |
| y          | 0.087622     | 0.099702     | 0.099325     |
| w          | 3.935519     | 0.266328     | 0.122574     |
| h          | 8.789259     | 1.120646     | 0.183937     |
| conf       | 33.698696    | 51.657539    | 55.038918    |
| cls        | 0.368801     | 0.409701     | 0.487944     |
| cls_acc    | 100.00%      | 100.00%      | 100.00%      |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.308153     | 0.314134     | 0.433198     |
| conf_noobj | 0.268605     | 0.391163     | 0.416380     |
+------------+--------------+--------------+--------------+
Total loss 156.631103515625
---- ETA 0:00:37.697671

---- [Epoch 0/2000, Batch 8/57] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 15           | 30           | 60           |
| loss       | 39.819099    | 46.499004    | 51.473125    |
| x          | 0.092698     | 0.096135     | 0.106848     |
| y          | 0.055413     | 0.069762     | 0.091548     |
| w          | 4.231538     | 0.784270     | 0.454928     |
| h          | 6.965583     | 1.269382     | 0.553979     |
| conf       | 28.187439    | 43.893917    | 49.825989    |
| cls        | 0.286428     | 0.385537     | 0.439834     |
| cls_acc    | 100.00%      | 100.00%      | 100.00%      |
| recall50   | 0.000000     | 0.000000     | 0.035714     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.007874     |
| conf_obj   | 0.257785     | 0.307955     | 0.450730     |
| conf_noobj | 0.227274     | 0.342219     | 0.385795     |
+------------+--------------+--------------+--------------+
Total loss 137.79122924804688
---- ETA 0:00:37.315741

---- [Epoch 0/2000, Batch 9/57] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 15           | 30           | 60           |
| loss       | 47.318920    | 50.155907    | 51.987705    |
| x          | 0.073157     | 0.089893     | 0.096906     |
| y          | 0.073818     | 0.080139     | 0.082365     |
| w          | 9.659940     | 1.043807     | 0.294443     |
| h          | 9.313881     | 2.925737     | 0.309880     |
| conf       | 27.887428    | 45.611019    | 50.764458    |
| cls        | 0.310695     | 0.405312     | 0.439651     |
| cls_acc    | 100.00%      | 100.00%      | 100.00%      |
| recall50   | 0.000000     | 0.000000     | 0.040000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.005208     |
| conf_obj   | 0.271461     | 0.317328     | 0.428925     |
| conf_noobj | 0.226013     | 0.353839     | 0.391157     |
+------------+--------------+--------------+--------------+
Total loss 149.4625244140625
---- ETA 0:00:37.089258

---- [Epoch 0/2000, Batch 10/57] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 12           | 24           | 48           |
| loss       | 26.600405    | 39.471378    | 46.552628    |
| x          | 0.059766     | 0.060431     | 0.082056     |
| y          | 0.116584     | 0.069668     | 0.025240     |
| w          | 0.733761     | 0.343165     | 0.139685     |
| h          | 1.773238     | 0.715863     | 0.150466     |
| conf       | 23.662550    | 37.947121    | 45.732658    |
| cls        | 0.254505     | 0.335131     | 0.422524     |
| cls_acc    | 100.00%      | 100.00%      | 100.00%      |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.181707     | 0.248364     | 0.360466     |
| conf_noobj | 0.192060     | 0.301474     | 0.358732     |
+------------+--------------+--------------+--------------+
Total loss 112.6244125366211
---- ETA 0:00:36.094961

---- [Epoch 0/2000, Batch 11/57] ----
+------------+--------------+--------------+--------------+
| Metrics    | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
+------------+--------------+--------------+--------------+
| grid_size  | 12           | 24           | 48           |
| loss       | 61.404385    | 42.252499    | 47.478542    |
| x          | 0.111068     | 0.103092     | 0.086435     |
| y          | 0.185376     | 0.193183     | 0.120116     |
| w          | 16.901545    | 0.558577     | 0.360661     |
| h          | 22.929956    | 3.363617     | 0.261616     |
| conf       | 21.127113    | 37.583675    | 46.200512    |
| cls        | 0.149327     | 0.450356     | 0.449204     |
| cls_acc    | 100.00%      | 100.00%      | 100.00%      |
| recall50   | 0.000000     | 0.000000     | 0.000000     |
| recall75   | 0.000000     | 0.000000     | 0.000000     |
| precision  | 0.000000     | 0.000000     | 0.000000     |
| conf_obj   | 0.243173     | 0.250932     | 0.365986     |
| conf_noobj | 0.172008     | 0.298216     | 0.362111     |
+------------+--------------+--------------+--------------+
Total loss 151.1354217529297

cls accuracy is not changing at all ..
during evaluation i am getting following error please explain 
 File "/home/ubuntu/projects/train-lesions-pytorch-yolov3/PyTorch-YOLOv3/test.py", line 53, in evaluate
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by OwlWisdom** [comment] 2019-06-27 12:43
I got the same issue,

"Traceback (most recent call last):
  File "train.py", line 160, in <module>
    batch_size=4,
  File "/home/yang/PyTorch-YOLOv3/test.py", line 53, in evaluate
    true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)
"

**Comment by ChandanVerma** [comment] 2019-07-22 11:40
The issue was solved by doing the multiscale training to false in line no. 38 train.py scripts. By default its True, you can change it to false and the issue will be solved.

**Comment by molyswu** [comment] 2019-08-02 07:17
Try to 38 train.py scripts.  True change it to false and the  same issue.

PyTorch-YOLOv3/test.py", line 53, in evaluate
true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
ValueError: not enough values to unpack (expected 3, got 0)

Thanks!

**Comment by davidefiocco** [comment] 2019-09-03 15:18
This issue seems a duplicate of https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/222 which has some solution hints and a pull request attached.

**Comment by mayaghaei** [comment] 2019-09-18 14:19
> +------------+--------------+--------------+--------------+
> | Metrics | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
> +------------+--------------+--------------+--------------+
> | grid_size | 15 | 30 | 60 |
> | loss | 46.969822 | 53.641315 | 56.019966 |
> | x | 0.089926 | 0.087395 | 0.087266 |
> | y | 0.087622 | 0.099702 | 0.099325 |
> | w | 3.935519 | 0.266328 | 0.122574 |
> | h | 8.789259 | 1.120646 | 0.183937 |
> | conf | 33.698696 | 51.657539 | 55.038918 |
> | cls | 0.368801 | 0.409701 | 0.487944 |
> | cls_acc | 100.00% | 100.00% | 100.00% |
> | recall50 | 0.000000 | 0.000000 | 0.000000 |
> | recall75 | 0.000000 | 0.000000 | 0.000000 |
> | precision | 0.000000 | 0.000000 | 0.000000 |
> | conf_obj | 0.308153 | 0.314134 | 0.433198 |
> | conf_noobj | 0.268605 | 0.391163 | 0.416380 |
> +------------+--------------+--------------+--------------+
> Total loss 156.631103515625
> ---- ETA 0:00:37.697671
> 
> ---- [Epoch 0/2000, Batch 8/57] ----
> +------------+--------------+--------------+--------------+
> | Metrics | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
> +------------+--------------+--------------+--------------+
> | grid_size | 15 | 30 | 60 |
> | loss | 39.819099 | 46.499004 | 51.473125 |
> | x | 0.092698 | 0.096135 | 0.106848 |
> | y | 0.055413 | 0.069762 | 0.091548 |
> | w | 4.231538 | 0.784270 | 0.454928 |
> | h | 6.965583 | 1.269382 | 0.553979 |
> | conf | 28.187439 | 43.893917 | 49.825989 |
> | cls | 0.286428 | 0.385537 | 0.439834 |
> | cls_acc | 100.00% | 100.00% | 100.00% |
> | recall50 | 0.000000 | 0.000000 | 0.035714 |
> | recall75 | 0.000000 | 0.000000 | 0.000000 |
> | precision | 0.000000 | 0.000000 | 0.007874 |
> | conf_obj | 0.257785 | 0.307955 | 0.450730 |
> | conf_noobj | 0.227274 | 0.342219 | 0.385795 |
> +------------+--------------+--------------+--------------+
> Total loss 137.79122924804688
> ---- ETA 0:00:37.315741
> 
> ---- [Epoch 0/2000, Batch 9/57] ----
> +------------+--------------+--------------+--------------+
> | Metrics | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
> +------------+--------------+--------------+--------------+
> | grid_size | 15 | 30 | 60 |
> | loss | 47.318920 | 50.155907 | 51.987705 |
> | x | 0.073157 | 0.089893 | 0.096906 |
> | y | 0.073818 | 0.080139 | 0.082365 |
> | w | 9.659940 | 1.043807 | 0.294443 |
> | h | 9.313881 | 2.925737 | 0.309880 |
> | conf | 27.887428 | 45.611019 | 50.764458 |
> | cls | 0.310695 | 0.405312 | 0.439651 |
> | cls_acc | 100.00% | 100.00% | 100.00% |
> | recall50 | 0.000000 | 0.000000 | 0.040000 |
> | recall75 | 0.000000 | 0.000000 | 0.000000 |
> | precision | 0.000000 | 0.000000 | 0.005208 |
> | conf_obj | 0.271461 | 0.317328 | 0.428925 |
> | conf_noobj | 0.226013 | 0.353839 | 0.391157 |
> +------------+--------------+--------------+--------------+
> Total loss 149.4625244140625
> ---- ETA 0:00:37.089258
> 
> ---- [Epoch 0/2000, Batch 10/57] ----
> +------------+--------------+--------------+--------------+
> | Metrics | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
> +------------+--------------+--------------+--------------+
> | grid_size | 12 | 24 | 48 |
> | loss | 26.600405 | 39.471378 | 46.552628 |
> | x | 0.059766 | 0.060431 | 0.082056 |
> | y | 0.116584 | 0.069668 | 0.025240 |
> | w | 0.733761 | 0.343165 | 0.139685 |
> | h | 1.773238 | 0.715863 | 0.150466 |
> | conf | 23.662550 | 37.947121 | 45.732658 |
> | cls | 0.254505 | 0.335131 | 0.422524 |
> | cls_acc | 100.00% | 100.00% | 100.00% |
> | recall50 | 0.000000 | 0.000000 | 0.000000 |
> | recall75 | 0.000000 | 0.000000 | 0.000000 |
> | precision | 0.000000 | 0.000000 | 0.000000 |
> | conf_obj | 0.181707 | 0.248364 | 0.360466 |
> | conf_noobj | 0.192060 | 0.301474 | 0.358732 |
> +------------+--------------+--------------+--------------+
> Total loss 112.6244125366211
> ---- ETA 0:00:36.094961
> 
> ---- [Epoch 0/2000, Batch 11/57] ----
> +------------+--------------+--------------+--------------+
> | Metrics | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 |
> +------------+--------------+--------------+--------------+
> | grid_size | 12 | 24 | 48 |
> | loss | 61.404385 | 42.252499 | 47.478542 |
> | x | 0.111068 | 0.103092 | 0.086435 |
> | y | 0.185376 | 0.193183 | 0.120116 |
> | w | 16.901545 | 0.558577 | 0.360661 |
> | h | 22.929956 | 3.363617 | 0.261616 |
> | conf | 21.127113 | 37.583675 | 46.200512 |
> | cls | 0.149327 | 0.450356 | 0.449204 |
> | cls_acc | 100.00% | 100.00% | 100.00% |
> | recall50 | 0.000000 | 0.000000 | 0.000000 |
> | recall75 | 0.000000 | 0.000000 | 0.000000 |
> | precision | 0.000000 | 0.000000 | 0.000000 |
> | conf_obj | 0.243173 | 0.250932 | 0.365986 |
> | conf_noobj | 0.172008 | 0.298216 | 0.362111 |
> +------------+--------------+--------------+--------------+
> Total loss 151.1354217529297
> 
> cls accuracy is not changing at all ..
> during evaluation i am getting following error please explain
> File "/home/ubuntu/projects/train-lesions-pytorch-yolov3/PyTorch-YOLOv3/test.py", line 53, in evaluate
> true_positives, pred_scores, pred_labels = [np.concatenate(x, 0) for x in list(zip(*sample_metrics))]
> ValueError: not enough values to unpack (expected 3, got 0)

Did you actually get a response to your first question? I mean, does anybody actually know why cls accuracy does not change at all? I am trying to train Yolo on my custom dataset with only one class.

**Comment by Flova** [comment] 2021-01-09 21:41
I think it is the expected behavior for one class. Because what would do wrong if there is only one choice. Does this solve your question?
The second issue is discussed in #178 btw.

**Comment by Flova** [comment] 2021-04-08 20:59
Sorry, I don't understand your question. Could you explain it further?

 `Metrics | YOLO Layer 0 | YOLO Layer 1 | YOLO Layer 2 | YOLO Layer 2 |`  also is part of an old version of the code. The printout changed.

To freeze a layer, iterate trough the model layers in the `train.py` after creating the model and set its `requires_grad` attribute to `False`.

**Comment by luforestal** [comment] 2021-04-09 13:05
Does this mean that I am currently training the entire model? Thank you much for your answer :)

**Comment by Flova** [comment] 2021-04-09 15:35
Exactly :)

**Closed by Flova** 2021-04-09 15:35 UTC
