### ISSUE TITLE
train on VOC data

### ISSUE THREAD

**Issue by JeasonUESTC** [eriklindernoren/PyTorch-YOLOv3#218] opened 2019-07-05 09:15 UTC
The original VOC data set was trained, and the results were very poor. There were few accurate boxes and many redundant boxes in the detection results, and the data set was compared without any problems.

**Comment by HaochenW** [comment] 2019-07-12 08:03
I have the same problem...

**Comment by www12345678** [comment] 2019-07-29 13:01
@JeasonUESTC
@HaochenW 
What big epochs do you choose?

**Comment by HaochenW** [comment] 2019-07-30 03:46
100 epoches @www12345678

**Comment by www12345678** [comment] 2019-07-31 07:45
@HaochenW
epochs=100, what's you map?

**Comment by ZhxJia** [comment] 2019-08-02 01:56
> @HaochenW
> epochs=100, what's you map?

my map is just 0.11

**Comment by Songtingt** [comment] 2019-12-12 01:17
> > @HaochenW
> > epochs=100, what's you map?
> 
> my map is just 0.11

Have you solved your problem? i have the same epoch with you and my map is 0.21

**Comment by abhiagwl4262** [comment] 2020-08-18 13:23
@HaochenW @ZhxJia @H-YunHui Did anyone figured it out ?

**Comment by Flova** [comment] 2021-02-02 14:36
Duplicate of #172

**Closed by Flova** 2021-02-02 14:36 UTC
