### ISSUE TITLE
mutil gpus

### ISSUE THREAD

**Issue by stevenXS** [eriklindernoren/PyTorch-YOLOv3#507] opened 2020-05-20 02:35 UTC
Has anyone solved the mutil-gpus traing probem?

**Comment by MinaGabriel** [comment] 2020-06-03 16:22
Did you find a solution for this?

**Comment by voodoopotato** [comment] 2020-06-11 15:44
I have found a solution to this. I leverage Pytorch distributed package with Nvidia Apex to train on 4 rtx 2080ti with a batch size of 80.

**Comment by jxhno1** [comment] 2020-06-17 08:34
how to do that for  leverage Pytorch distributed package with Nvidia Apex to train on 4 rtx 2080ti with a batch size of 80. @voodoopotato Thank you!

**Comment by jxhno1** [comment] 2020-06-17 08:35
How to do that for your saying 'leverage Pytorch distributed package with Nvidia Apex to train on 4 rtx 2080ti with a batch size of 80'  Is that easy or not, Thank you!

**Comment by voodoopotato** [comment] 2020-06-18 16:38
@jxhno1 it is definitely not very hard to do. It is just time-consuming for first-timer. You will have to dig deep into PyTorch Cuda API functionalities. But once you are able to deploy one model, you can do for all of them. It is something everyone should pick up since it can be applied generally.

**Comment by genqiaolynn** [comment] 2021-01-21 14:15
can you solute multi gpu for training?Thanks!

**Comment by Flova** [comment] 2021-08-02 13:33
Duplicate of #520

**Closed by Flova** 2021-08-02 13:33 UTC
