### ISSUE TITLE
out of cuda memory 

### ISSUE THREAD

**Issue by kuazhangxiaoai** [eriklindernoren/PyTorch-YOLOv3#619] opened 2021-01-30 06:32 UTC
Good code, But 1080Ti gpu is appied for training yolov3. When I training my yolov3 and set batch size as 1, 10.2/11 GiB of GPU memory is occupied. Why? How much GPU memory is need for taining yolov3? I just want to set batch size as 4.

**Comment by Flova** [comment] 2021-01-30 11:00
That is strange. I sometimes train on a 1080 and use a batch size of 10. What is you input resolution?

**Comment by kuazhangxiaoai** [comment] 2021-01-30 14:20
> That is strange. I sometimes train on a 1080 and use a batch size of 10. What is you input resolution?

My input data is coco2014 dataset. The allocated memory is continuously increasing with calling the yolov3 model forward function. Why the gpu allocates memory repeatedly?

**Comment by Flova** [comment] 2021-01-30 16:30
This is strange. Does it only occur on the current master? And which CUDA version did you use?

**Comment by kuazhangxiaoai** [comment] 2021-01-31 02:13
> oes it only occur on the current master?

No, it happened in various yolov3 pytorch programs. and I use CUDA10.1 and cudnn7.6.5

**Comment by Flova** [comment] 2021-01-31 15:51
That seems strange. Sorry but I have no idea and I am not able to reproduce this issue.

**Comment by kuazhangxiaoai** [comment] 2021-02-02 01:50
> That seems strange. Sorry but I have no idea and I am not able to reproduce this issue.

I have already solved this problem by delete Log module and tensorflow library, bacause the tensorflow will cost most of your gpu memory when starting.

**Comment by Flova** [comment] 2021-02-02 13:40
Ah okay. The TensorFlow dependency also got removed from the current master. PyTorch has the same log functions.
I am closing this now. Feel free to reopen for further questions

**Closed by Flova** 2021-02-02 13:40 UTC
