### ISSUE TITLE
When I was training my dataset, I made the following error

### ISSUE THREAD

**Issue by Zzheng-6** [eriklindernoren/PyTorch-YOLOv3#661] opened 2021-04-10 01:02 UTC
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    dataset = ListDataset(train_path, multiscale=opt.multiscale_training, img_size=opt.img_size, transform=AUGMENTATION_TRANSFORMS)
  File "/content/drive/Shareddrives/1349478794@qq.com/PyTorch-YOLOv3-master/utils1/datasets.py", line 73, in __init__
    for path in self.img_files
  File "/content/drive/Shareddrives/1349478794@qq.com/PyTorch-YOLOv3-master/utils1/datasets.py", line 73, in <listcomp>
    for path in self.img_files
TypeError: a bytes-like object is required, not 'str'

**Comment by Flova** [comment] 2021-04-10 13:14
Could you send me the code that opens the file? It's a few lines above the for loop from the traceback. This error occurs if one opens a file with "rb" instead of "r". Could you check if this is the case? The master branch uses an "r" but maybe there are changes in this line or something similar.

**Comment by Zzheng-6** [comment] 2021-04-10 14:09
This is dataset.py But it's strange when I run it again train.py The previous mistake is gone, and this new mistake appears.
The new mistakes are as follows:



Namespace(batch_size=1, checkpoint_interval=1, compute_map=False, data_config='config/custom.data', epochs=100, evaluation_interval=1, gradient_accumulations=2, img_size=416, logdir='logs', model_def='config/yolov3-custom.cfg', multiscale_training=True, n_cpu=8, pretrained_weights='weights/darknet53.conv.74', verbose=False) 2021-04-10 14:05:03.616355: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0 Traceback (most recent call last):   File "train.py", line 73, in <module&gt;     dataset = ListDataset(train_path, multiscale=opt.multiscale_training, img_size=opt.img_size, transform=AUGMENTATION_TRANSFORMS)   File ***@***.***/PyTorch-YOLOv3-master/utils1/datasets.py", line 69, in __init__     self.img_files = file.readlines()   File "/usr/lib/python3.7/codecs.py", line 322, in decode     (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 4755: invalid continuation byte
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月10日(星期六) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] When I was training my dataset, I made the following error (#661)





 
Could you send me the code that opens the file? It's a few lines above the for loop from the traceback. This error occurs if one opens a file with "rb" instead of "r". Could you check if this is the case? The master branch uses an "r" but maybe there are changes in this line or something similar.

**Comment by Flova** [comment] 2021-04-10 17:25
See #374

**Comment by Zzheng-6** [comment] 2021-04-11 00:51
Just like this
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eriklindernoren/PyTorch-YOLOv3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 凌晨1:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eriklindernoren/PyTorch-YOLOv3] When I was training my dataset, I made the following error (#661)





 
See #374

**Comment by Flova** [comment] 2021-04-11 19:06
I close this issue because it is a duplicate of #374. Okay?

**Closed by Flova** 2021-04-11 19:06 UTC
