### ISSUE TITLE
multiple gpus?

### ISSUE THREAD

**Issue by aliborji** [eriklindernoren/PyTorch-YOLOv3#181] opened 2019-05-17 20:16 UTC
Is it possible to train the model (this code) on multiple gpus?

**Comment by wilkice** [comment] 2019-05-19 05:02
Not support. You can change the code to support. reference: [PyTorch MULTI-GPU EXAMPLES](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html)

**Comment by kaikaizhu** [comment] 2019-06-19 08:22
@aliborji ,@wilkice
I want to use multi-GPU training. Did you add it successfully? I made a mistake when I added it.

RuntimeError: CUDA error: device-side assert triggered.

**Comment by www12345678** [comment] 2019-07-31 02:07
@kaikaizhu 
I have the same question, and do you solve it now?

**Comment by MichaelCong** [comment] 2019-08-05 00:37
I have the same question, and do you solve it now?

**Comment by YIYIZH** [comment] 2019-08-06 06:38
> @aliborji ,@wilkice
> I want to use multi-GPU training. Did you add it successfully? I made a mistake when I added it.
> 
> RuntimeError: CUDA error: device-side assert triggered.

I met the same error, and I think the problem comes from here.
 loss, outputs = model(imgs, targets)
while i use 4 gpus, I found the imgs and targets are divided equally into 4 gpus. The problem is that the targets should not be equally splitted since each img have different number of targets(bboxes).

One of the solution is to do like this:
outputs = model(imgs)
loss = compute_loss(outputs, targets) # you have to write a new function to compute the loss

Another is to find the size of the longest targets of imgs in one batch, and pad zeros to each target into the same length. such that targets can correspond to the imgs.

If anyone has better solution, pls tell me. Thx.

**Comment by GangHu1993** [comment] 2019-08-21 12:11
I have the same question, 

> > @aliborji ,@wilkice
> > I want to use multi-GPU training. Did you add it successfully? I made a mistake when I added it.
> > RuntimeError: CUDA error: device-side assert triggered.
> 
> I met the same error, and I think the problem comes from here.
> loss, outputs = model(imgs, targets)
> while i use 4 gpus, I found the imgs and targets are divided equally into 4 gpus. The problem is that the targets should not be equally splitted since each img have different number of targets(bboxes).
> 
> One of the solution is to do like this:
> outputs = model(imgs)
> loss = compute_loss(outputs, targets) # you have to write a new function to compute the loss
> 
> Another is to find the size of the longest targets of imgs in one batch, and pad zeros to each target into the same length. such that targets can correspond to the imgs.
> 
> If anyone has better solution, pls tell me. Thx.

I have same probliem, do you have solved this ?

**Comment by yangzhaonan18** [comment] 2019-09-11 06:01
多GPU加载模型和数据官网有教程，加载权重怎么弄，求个学习链接，谢谢
Multi-GPU loading model and data official website have tutorials, how to load weights, ask for a learning link, thank you

**Comment by ywatanabe1989** [comment] 2019-10-31 14:11
https://github.com/ywatanabe1989/PyTorch-gaussian-YOLOv3-1D/
Although there might be mistakes (at least, the print log output is broken now.) and it's not sophisticated at all, I tried to implement the multi-GPU functioning.

Please give me some feedback. :)

**Comment by ujsyehao** [comment] 2019-11-17 04:24
@YIYIZH Hi, I solve the problem using your proposed method(Another is to find the size of the longest targets of imgs in one batch, and pad zeros to each target into the same length).

**Comment by ujsyehao** [comment] 2019-11-17 04:43
You can refer to https://github.com/ujsyehao/yolov3-multigpu

**Comment by sakurasakura1996** [comment] 2020-03-16 02:37
> > @aliborji ,@wilkice
> > I want to use multi-GPU training. Did you add it successfully? I made a mistake when I added it.
> > RuntimeError: CUDA error: device-side assert triggered.
> 
> I met the same error, and I think the problem comes from here.
> loss, outputs = model(imgs, targets)
> while i use 4 gpus, I found the imgs and targets are divided equally into 4 gpus. The problem is that the targets should not be equally splitted since each img have different number of targets(bboxes).
> 
> One of the solution is to do like this:
> outputs = model(imgs)
> loss = compute_loss(outputs, targets) # you have to write a new function to compute the loss
> 
> Another is to find the size of the longest targets of imgs in one batch, and pad zeros to each target into the same length. such that targets can correspond to the imgs.
> 
> If anyone has better solution, pls tell me. Thx.
Did you solve the problem,I want to run the code on my custom data with one GPU,but I found I am training on CPU

**Comment by Flova** [comment] 2021-02-02 14:12
Duplicate of #265 #507 #290

**Closed by Flova** 2021-02-02 14:12 UTC
